spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dive
    password: dive
    url: jdbc:mysql://localhost:3306/dive?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: localhost:9200
      username: elastic
      password: MyPw123
#    hibernate:
#      ddl-auto: create-drop
  batch:
    job:
      enabled: false # ?? ???? ?? ???? ??
      jdbc:
        initialize-schema: always
server:
  port: 8082
logging:
  level:
    org.hibernate: DEBUG