spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dive
    password: dive
    url: jdbc:mysql://localhost:3306/dive?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: create-drop
  mail:
    host: smtp.naver.com
    port: 587
    username: secret
    password: secret
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        default-encoding: UTF-8
  cloud:
    gcp:
      credentials:
        location: gcs/haechorom-4139b1a25e41.json
      project-id: haechorom
      storage:
        bucket: haechorom
logging:
  level:
    org.hibernate: DEBUG