version: '3.8'
services:
  dive-mysql:
    image: mysql:latest
    container_name: dive-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dive
      MYSQL_USER: dive
      MYSQL_PASSWORD: dive
      TZ: Asia/Seoul
    command: [ "--character-set-server=utf8mb4" ]
    ports:
      - "3306:3306"
    networks:
      - dive-network
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
  dive-adminer:
    image: adminer:latest
    container_name: dive-adminer
    environment:
      ADMINER_DEFAULT_SERVER: dive-mysql
    ports:
      - "18080:8080"
    networks:
      - dive-network
  dive-redis:
    image: redis:latest
    container_name: dive-redis
    ports:
      - "6379:6379"
    networks:
      - dive-network
networks:
  dive-network:
    driver: bridge
